name: SSH Handshake

on:
  push:
    branches:
      - main

jobs:
  ssh_handshake:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-3-224-114-58.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Use the SSH private key from GitHub Secrets
          script: |
            echo "SSH connection successful"
