name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ec2-3-224-114-58.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv * /app
            sudo apt update
            npm install
            npm run build
            pm2 start server.js
